# Generated by Django 4.0.3 on 2022-06-16 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0003_alter_hat_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hats', to='hats_rest.locationvo'),
        ),
        migrations.AlterField(
            model_name='hat',
            name='picture_url',
            field=models.URLField(null=True),
        ),
    ]
